diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "wheel_left_joint"
  right_wheel: "wheel_right_joint"
  publish_rate: 50.0
  pose_covariance_diagonal:
    [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal:
    [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation: 0.184
  wheel_radius: 0.032

  cmd_vel_timeout: 0.25

  base_frame_id: base_footprint

  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0 # m/s
      min_velocity: -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration: 0.8 # m/s^2
      min_acceleration: -0.4 # m/s^2
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 1.5708 # pi/2 rad/s
      has_acceleration_limits: true
      max_acceleration: 1.1781 # 3pi/8 rad/s^2
